In [107]:
import pandas as pd
import numpy as np

# Set a random seed so everyone gets the same dataset
np.random.seed(42)

data = {
    "patient_id": [
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 103, 107, 122, 123
    ],
    "animal_type": [
        "dog", "cat", "dog", "rabbit", "cat",
        "dog", "cat", "bird", "dog", "cat",
        "dog", "rabbit", "cat", "dog", "bird",
        "cat", "dog", "cat", "dog", "rabbit",
        "cat", None, "cat", "dog", "bird"
    ],
    "age_years": [
        3, 7, 2, 4, 1,
        5, 8, 2, 6, 3,
        None, 1, 4, 9, 3,
        2, 7, None, 4, 2,
        6, 2, 8, None, 1
    ],
    "weight_kg": [
        18.2, 4.1, 22.5, 1.8, 3.9,
        31.0, 4.7, 0.09, 14.3, 5.2,
        27.8, 2.1, 999.0, 10.5, 0.11,
        3.8, 24.1, 4.4, -5.0, 1.9,
        5.1, 22.5, 4.7, 16.3, 0.08
    ],
    "visit_reason": [
        "checkup", "checkup", "vaccination", "checkup", "dental",
        "injury", "checkup", "checkup", "dental", "vaccination",
        "checkup", "dental", "injury", "checkup", "vaccination",
        "injury", "vaccination", "checkup", "dental", "checkup",
        "vaccination", "vaccination", "checkup", "injury", "checkup"
    ],
    "visit_cost_usd": [
        85.0, 70.0, None, 65.0, 120.0,
        None, 75.0, 60.0, 130.0, 70.0,
        80.0, 115.0, 90.0, 85.0, 60.0,
        None, 95.0, 70.0, 125.0, 65.0,
        70.0, None, 75.0, 90.0, 60.0
    ],
    "follow_up_needed": [
        False, False, True, False, True,
        True, False, False, True, False,
        False, True, True, False, False,
        True, False, False, True, False,
        False, True, False, True, False
    ]
}

clinic = pd.DataFrame(data)
print("Dataset created. Shape:", clinic.shape)
clinic.head()
clinic

Dataset created. Shape: (25, 7)

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,101,dog,3.0,18.20,checkup,85.0,False
1,102,cat,7.0,4.10,checkup,70.0,False
2,103,dog,2.0,22.50,vaccination,NaN,True
3,104,rabbit,4.0,1.80,checkup,65.0,False
4,105,cat,1.0,3.90,dental,120.0,True
5,106,dog,5.0,31.00,injury,NaN,True
6,107,cat,8.0,4.70,checkup,75.0,False
7,108,bird,2.0,0.09,checkup,60.0,False
8,109,dog,6.0,14.30,dental,130.0,True
9,110,cat,3.0,5.20,vaccination,70.0,False
10,111,dog,NaN,27.80,checkup,80.0,False
11,112,rabbit,1.0,2.10,dental,115.0,True
12,113,cat,4.0,999.00,injury,90.0,True
13,114,dog,9.0,10.50,checkup,85.0,False
14,115,bird,3.0,0.11,vaccination,60.0,False
15,116,cat,2.0,3.80,injury,NaN,True
16,117,dog,7.0,24.10,vaccination,95.0,False
17,118,cat,NaN,4.40,checkup,70.0,False
18,119,dog,4.0,-5.00,dental,125.0,True
19,120,rabbit,2.0,1.90,checkup,65.0,False
20,121,cat,6.0,5.10,vaccination,70.0,False
21,103,None,2.0,22.50,vaccination,NaN,True
22,107,cat,8.0,4.70,checkup,75.0,False
23,122,dog,NaN,16.30,injury,90.0,True
24,123,bird,1.0,0.08,checkup,60.0,False

In [108]:
#Task 1
clinic.info()
# rows: 25 columns: 7
# missing values: age_years, animal_type, visit_cost
# follow_up_needed: bool

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   patient_id        25 non-null     int64
 1   animal_type       24 non-null     object
 2   age_years         22 non-null     float64
 3   weight_kg         25 non-null     float64
 4   visit_reason      25 non-null     object
 5   visit_cost_usd    21 non-null     float64
 6   follow_up_needed  25 non-null     bool
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 1.3+ KB

In [109]:
clinic.describe()
# Min weight kg: -5.00000
#Max weight kg: 999.00000

       patient_id  age_years   weight_kg  visit_cost_usd
count   25.000000  22.000000   25.000000       21.000000
mean   111.440000   4.090909   48.927200       83.571429
std      6.801225   2.524340  198.178411       21.974011
min    101.000000   1.000000   -5.000000       60.000000
25%    106.000000   2.000000    2.100000       70.000000
50%    111.000000   3.500000    4.700000       75.000000
75%    117.000000   6.000000   18.200000       90.000000
max    123.000000   9.000000  999.000000      130.000000

In [110]:
clinic["visit_reason"].value_counts()
# most common reason for visit = checkup

visit_reason
checkup        11
vaccination     6
dental          4
injury          4
Name: count, dtype: int64

## Task 2

In [111]:
clinic.isna()
clinic

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,101,dog,3.0,18.20,checkup,85.0,False
1,102,cat,7.0,4.10,checkup,70.0,False
2,103,dog,2.0,22.50,vaccination,NaN,True
3,104,rabbit,4.0,1.80,checkup,65.0,False
4,105,cat,1.0,3.90,dental,120.0,True
5,106,dog,5.0,31.00,injury,NaN,True
6,107,cat,8.0,4.70,checkup,75.0,False
7,108,bird,2.0,0.09,checkup,60.0,False
8,109,dog,6.0,14.30,dental,130.0,True
9,110,cat,3.0,5.20,vaccination,70.0,False
10,111,dog,NaN,27.80,checkup,80.0,False
11,112,rabbit,1.0,2.10,dental,115.0,True
12,113,cat,4.0,999.00,injury,90.0,True
13,114,dog,9.0,10.50,checkup,85.0,False
14,115,bird,3.0,0.11,vaccination,60.0,False
15,116,cat,2.0,3.80,injury,NaN,True
16,117,dog,7.0,24.10,vaccination,95.0,False
17,118,cat,NaN,4.40,checkup,70.0,False
18,119,dog,4.0,-5.00,dental,125.0,True
19,120,rabbit,2.0,1.90,checkup,65.0,False
20,121,cat,6.0,5.10,vaccination,70.0,False
21,103,None,2.0,22.50,vaccination,NaN,True
22,107,cat,8.0,4.70,checkup,75.0,False
23,122,dog,NaN,16.30,injury,90.0,True
24,123,bird,1.0,0.08,checkup,60.0,False

In [112]:
clinic.isna().sum()
# age_years and visit_cost_usd have the most missing values
clinic

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,101,dog,3.0,18.20,checkup,85.0,False
1,102,cat,7.0,4.10,checkup,70.0,False
2,103,dog,2.0,22.50,vaccination,NaN,True
3,104,rabbit,4.0,1.80,checkup,65.0,False
4,105,cat,1.0,3.90,dental,120.0,True
5,106,dog,5.0,31.00,injury,NaN,True
6,107,cat,8.0,4.70,checkup,75.0,False
7,108,bird,2.0,0.09,checkup,60.0,False
8,109,dog,6.0,14.30,dental,130.0,True
9,110,cat,3.0,5.20,vaccination,70.0,False
10,111,dog,NaN,27.80,checkup,80.0,False
11,112,rabbit,1.0,2.10,dental,115.0,True
12,113,cat,4.0,999.00,injury,90.0,True
13,114,dog,9.0,10.50,checkup,85.0,False
14,115,bird,3.0,0.11,vaccination,60.0,False
15,116,cat,2.0,3.80,injury,NaN,True
16,117,dog,7.0,24.10,vaccination,95.0,False
17,118,cat,NaN,4.40,checkup,70.0,False
18,119,dog,4.0,-5.00,dental,125.0,True
19,120,rabbit,2.0,1.90,checkup,65.0,False
20,121,cat,6.0,5.10,vaccination,70.0,False
21,103,None,2.0,22.50,vaccination,NaN,True
22,107,cat,8.0,4.70,checkup,75.0,False
23,122,dog,NaN,16.30,injury,90.0,True
24,123,bird,1.0,0.08,checkup,60.0,False

## Task 3

In [113]:
clinic = clinic.dropna(subset =['animal_type'])
clinic

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,101,dog,3.0,18.20,checkup,85.0,False
1,102,cat,7.0,4.10,checkup,70.0,False
2,103,dog,2.0,22.50,vaccination,NaN,True
3,104,rabbit,4.0,1.80,checkup,65.0,False
4,105,cat,1.0,3.90,dental,120.0,True
5,106,dog,5.0,31.00,injury,NaN,True
6,107,cat,8.0,4.70,checkup,75.0,False
7,108,bird,2.0,0.09,checkup,60.0,False
8,109,dog,6.0,14.30,dental,130.0,True
9,110,cat,3.0,5.20,vaccination,70.0,False
10,111,dog,NaN,27.80,checkup,80.0,False
11,112,rabbit,1.0,2.10,dental,115.0,True
12,113,cat,4.0,999.00,injury,90.0,True
13,114,dog,9.0,10.50,checkup,85.0,False
14,115,bird,3.0,0.11,vaccination,60.0,False
15,116,cat,2.0,3.80,injury,NaN,True
16,117,dog,7.0,24.10,vaccination,95.0,False
17,118,cat,NaN,4.40,checkup,70.0,False
18,119,dog,4.0,-5.00,dental,125.0,True
19,120,rabbit,2.0,1.90,checkup,65.0,False
20,121,cat,6.0,5.10,vaccination,70.0,False
22,107,cat,8.0,4.70,checkup,75.0,False
23,122,dog,NaN,16.30,injury,90.0,True
24,123,bird,1.0,0.08,checkup,60.0,False

In [114]:
clinic.shape
# We lost one row. 24 rows remain.

(24, 7)

## Task 4

In [115]:
median_age = clinic["age_years"].median()
print(median_age)
clinic['age_years'] = clinic['age_years'].fillna(median_age)

4.0

C:\Users\Lemons\AppData\Local\Temp\ipykernel_3432\828878196.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clinic['age_years'] = clinic['age_years'].fillna(median_age)

In [116]:
print(clinic["age_years"].isna().sum())

0

## Task 5

In [117]:
clinic["visit_cost_usd"] = clinic["visit_cost_usd"].fillna(
    clinic.groupby("visit_reason")["visit_cost_usd"]
    .transform("median")
)

C:\Users\Lemons\AppData\Local\Temp\ipykernel_3432\767335553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clinic["visit_cost_usd"] = clinic["visit_cost_usd"].fillna(

In [118]:
clinic["visit_cost_usd"].isna().sum()

np.int64(0)

There are different costs associated with each visit reason. This is why you would group by that column.

## Task 6

In [119]:
clinic[clinic["weight_kg"] <= 0]

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
18,119,dog,4.0,-5.0,dental,125.0,True

In [120]:
clinic[clinic["weight_kg"] > 200]

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
12,113,cat,4.0,999.0,injury,90.0,True

In [121]:
clinic.loc[(clinic["weight_kg"] <= 0), "weight_kg"] = np.nan
clinic.loc[(clinic["weight_kg"] > 200), "weight_kg"] = np.nan

In [122]:
clinic["weight_kg"].isna().sum()
clinic

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,101,dog,3.0,18.20,checkup,85.0,False
1,102,cat,7.0,4.10,checkup,70.0,False
2,103,dog,2.0,22.50,vaccination,70.0,True
3,104,rabbit,4.0,1.80,checkup,65.0,False
4,105,cat,1.0,3.90,dental,120.0,True
5,106,dog,5.0,31.00,injury,90.0,True
6,107,cat,8.0,4.70,checkup,75.0,False
7,108,bird,2.0,0.09,checkup,60.0,False
8,109,dog,6.0,14.30,dental,130.0,True
9,110,cat,3.0,5.20,vaccination,70.0,False
10,111,dog,4.0,27.80,checkup,80.0,False
11,112,rabbit,1.0,2.10,dental,115.0,True
12,113,cat,4.0,NaN,injury,90.0,True
13,114,dog,9.0,10.50,checkup,85.0,False
14,115,bird,3.0,0.11,vaccination,60.0,False
15,116,cat,2.0,3.80,injury,90.0,True
16,117,dog,7.0,24.10,vaccination,95.0,False
17,118,cat,4.0,4.40,checkup,70.0,False
18,119,dog,4.0,NaN,dental,125.0,True
19,120,rabbit,2.0,1.90,checkup,65.0,False
20,121,cat,6.0,5.10,vaccination,70.0,False
22,107,cat,8.0,4.70,checkup,75.0,False
23,122,dog,4.0,16.30,injury,90.0,True
24,123,bird,1.0,0.08,checkup,60.0,False

## Task 7

In [123]:
clinic[clinic.duplicated()]

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
22,107,cat,8.0,4.7,checkup,75.0,False

In [124]:
clinic = clinic.drop_duplicates()
clinic

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,101,dog,3.0,18.20,checkup,85.0,False
1,102,cat,7.0,4.10,checkup,70.0,False
2,103,dog,2.0,22.50,vaccination,70.0,True
3,104,rabbit,4.0,1.80,checkup,65.0,False
4,105,cat,1.0,3.90,dental,120.0,True
5,106,dog,5.0,31.00,injury,90.0,True
6,107,cat,8.0,4.70,checkup,75.0,False
7,108,bird,2.0,0.09,checkup,60.0,False
8,109,dog,6.0,14.30,dental,130.0,True
9,110,cat,3.0,5.20,vaccination,70.0,False
10,111,dog,4.0,27.80,checkup,80.0,False
11,112,rabbit,1.0,2.10,dental,115.0,True
12,113,cat,4.0,NaN,injury,90.0,True
13,114,dog,9.0,10.50,checkup,85.0,False
14,115,bird,3.0,0.11,vaccination,60.0,False
15,116,cat,2.0,3.80,injury,90.0,True
16,117,dog,7.0,24.10,vaccination,95.0,False
17,118,cat,4.0,4.40,checkup,70.0,False
18,119,dog,4.0,NaN,dental,125.0,True
19,120,rabbit,2.0,1.90,checkup,65.0,False
20,121,cat,6.0,5.10,vaccination,70.0,False
23,122,dog,4.0,16.30,injury,90.0,True
24,123,bird,1.0,0.08,checkup,60.0,False

In [125]:
clinic.shape
# confirms dropped one row

(23, 7)

## Task 8

In [126]:
clinic.info()
## We only have null values in "weight_kg", and we have one less row.

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 24
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   patient_id        23 non-null     int64
 1   animal_type       23 non-null     object
 2   age_years         23 non-null     float64
 3   weight_kg         21 non-null     float64
 4   visit_reason      23 non-null     object
 5   visit_cost_usd    23 non-null     float64
 6   follow_up_needed  23 non-null     bool
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 1.3+ KB

In [127]:
clinic.isna().sum()
## Yes, "weight_kg" still has NaN values

patient_id          0
animal_type         0
age_years           0
weight_kg           2
visit_reason        0
visit_cost_usd      0
follow_up_needed    0
dtype: int64

In [128]:
clinic.describe()
## Yes

       patient_id  age_years  weight_kg  visit_cost_usd
count    23.00000  23.000000  21.000000       23.000000
mean    112.00000   4.000000   9.618095       83.913043
std       6.78233   2.276361   9.854323       21.157232
min     101.00000   1.000000   0.080000       60.000000
25%     106.50000   2.000000   2.100000       70.000000
50%     112.00000   4.000000   4.700000       80.000000
75%     117.50000   5.500000  16.300000       90.000000
max     123.00000   9.000000  31.000000      130.000000

In [129]:
clinic.duplicated().sum()

## Remaining Nulls: 2
## Weight Min: .08kg
## Weight Max: 31.0kg
## Duplicate Rows: 0

np.int64(0)

- There is not a reliable way to assume what type an animal is, while missing ages could be reasonably assumed based off the median.

- There is a large variation in cost between reasons for visits, so it would be unreliable to assume the cost as a whole.

-  We have a relatively small data set, so it would be beneficial to keep as many samples as possible. Additionally, those rows could still be used for variables that don't involve weight.

## Task 9

In [130]:
clinic["weight_kg"] = clinic["weight_kg"].clip(lower=.05, upper=80)
clinic["weight_kg"].describe()
clinic

C:\Users\Lemons\AppData\Local\Temp\ipykernel_3432\3096767746.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clinic["weight_kg"] = clinic["weight_kg"].clip(lower=.05, upper=80)

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,101,dog,3.0,18.20,checkup,85.0,False
1,102,cat,7.0,4.10,checkup,70.0,False
2,103,dog,2.0,22.50,vaccination,70.0,True
3,104,rabbit,4.0,1.80,checkup,65.0,False
4,105,cat,1.0,3.90,dental,120.0,True
5,106,dog,5.0,31.00,injury,90.0,True
6,107,cat,8.0,4.70,checkup,75.0,False
7,108,bird,2.0,0.09,checkup,60.0,False
8,109,dog,6.0,14.30,dental,130.0,True
9,110,cat,3.0,5.20,vaccination,70.0,False
10,111,dog,4.0,27.80,checkup,80.0,False
11,112,rabbit,1.0,2.10,dental,115.0,True
12,113,cat,4.0,NaN,injury,90.0,True
13,114,dog,9.0,10.50,checkup,85.0,False
14,115,bird,3.0,0.11,vaccination,60.0,False
15,116,cat,2.0,3.80,injury,90.0,True
16,117,dog,7.0,24.10,vaccination,95.0,False
17,118,cat,4.0,4.40,checkup,70.0,False
18,119,dog,4.0,NaN,dental,125.0,True
19,120,rabbit,2.0,1.90,checkup,65.0,False
20,121,cat,6.0,5.10,vaccination,70.0,False
23,122,dog,4.0,16.30,injury,90.0,True
24,123,bird,1.0,0.08,checkup,60.0,False

## Task 10

In [131]:
clinic = clinic.dropna(subset="weight_kg")
clinic.shape
## 21 Rows

(21, 7)

## Task 11

In [ ]:
duplicate = clinic[clinic.duplicated(subset=["patient_id"], keep=False)]
##This upsets me